name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build Mod
      uses: geode-sdk/build-geode-mod@main
      with:
        build-config: Release
